# Generated by Django 5.1.7 on 2025-07-14 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_comment_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
